### ISSUE TITLE
Missing highlight of filename

### ISSUE THREAD

**Issue by ThomasArdal** [elmahio/netStack.js#2]
When parsing the following stacktrace, the filename in the second line isn't highlighted:

```
System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Elmah.Io.Web.Infrastructure.Validation.ValidateOrganisation.HasAdmin(String userId) in D:\a\1\s\src\Elmah.Io\Infrastructure\Validation\Validater.cs:line 62
   at Elmah.Io.Web.WebApi.InvoicesController.All(String organisationId) in D:\a\1\s\src\Elmah.Io\WebApi\InvoicesController.cs:line 63
```

![stracktrace](https://user-images.githubusercontent.com/563206/39171162-3972422e-479e-11e8-96e6-86d4fb5f6f8f.png)

Output HTML:

```html
<div>System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at <span class="st-frame"><span class="st-type">Elmah.Io.Web.Infrastructure.Validation.ValidateOrganisation</span>.<span class="st-method">HasAdmin</span><span class="st-frame-params">(<span class="st-param-type">String</span> <span class="st-param-name">userId</span>)</span></span> in D:\a\1\s\src\Elmah.Io\Infrastructure\Validation\Validater.cs:<span class="st-line">line 62</span>
   at <span class="st-frame"><span class="st-type">Elmah.Io.Web.WebApi.InvoicesController</span>.<span class="st-method">All</span><span class="st-frame-params">(<span class="st-param-type">String</span> <span class="st-param-name">organisationId</span>)</span></span> in <span class="st-file">D:\a\1\s\src\Elmah.Io\WebApi\InvoicesController.cs</span>:<span class="st-line">line 63</span>
</div>
```

**Comment by ZsharE** [comment]
Missing because you had an old version. With the latest version, everything works great.

**Comment by ThomasArdal** [comment]
That's weird. The [version on elmah.io](https://elmah.io/scripts/stacktrace.js) is 1.0.2 and when diffing the file from the website with the one you just pushed, they are identical.

**Comment by ZsharE** [comment]
So it's working or not ? 😄

**Comment by ThomasArdal** [comment]
It's not working on the website. The screenshot and generated HTML are taken directly from the site :smile:

So it's working in a fiddle?

**Comment by ZsharE** [comment]
HTML Output:

```html
<code class="nohighlight stacktrace">System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at <span class="st-frame"><span class="st-type">Elmah.Io.Web.Infrastructure.Validation.ValidateOrganisation</span>.<span class="st-method">HasAdmin</span><span class="st-frame-params">(<span class="st-param-type">String</span> <span class="st-param-name">userId</span>)</span></span> in <span class="st-file">D:\a\1\s\src\Elmah.Io\Infrastructure\Validation\Validater.cs</span>:<span class="st-line">line 62</span>
   at <span class="st-frame"><span class="st-type">Elmah.Io.Web.WebApi.InvoicesController</span>.<span class="st-method">All</span><span class="st-frame-params">(<span class="st-param-type">String</span> <span class="st-param-name">organisationId</span>)</span></span> in <span class="st-file">D:\a\1\s\src\Elmah.Io\WebApi\InvoicesController.cs</span>:<span class="st-line">line 63</span>
</code>

**Comment by ThomasArdal** [comment]
Weird. I don't remember if you have a user on elmah.io. Maybe I could publish that stacktrace to a log on your account to help you see what's going on inside the production version.
